[build]
  command = "echo 'Static site'"
  publish = "."

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[context.production.environment]
  MARZBAN_URL = "https://powervpn01.duckdns.org:8000"
  MARZBAN_LOGIN = "CSgi3HHvSg"
  MARZBAN_PASSWORD = "XY5Rj9XPlj"
  # URL бот-сервера — trial.js сохраняет сюда данные триала
  BOT_API_URL = "http://213.165.41.80:8080"
